no_money_phrases = [
    "no money",
    "don't have",
    "not got",
    "cant afford",
    "can't",
    "no",
    "too expensive",
    "too much",
    "broke",
    "poor",
    "no funds",
    "insufficient funds",
    "later",
    "not now",
    "maybe next time",
    "no money",
    "dont have the money",
    "i dont have 300",
    "i haven't got 300",
    "i cant afford 300",
    "i can't afford it",
    "cant afford",
    "can't afford it",
    "cannot afford",
    "haven't got it",
    "havent got it",
    "not got it",
    "not got that",
    "can't do it right now",
    "cant do it right now",
    "don't have enough",
    "no",
    "too expensive",
    "too much",
    "its too much",
    "it's too much",
    "that's too much",
    "thats too much",
    "way too much",
    "broke",
    "i'm broke",
    "im broke",
    "i am broke",
    "poor",
    "no funds",
    "zero funds",
    "not enough funds",
    "insufficient funds",
    "later",
    "not now",
    "maybe next time",
    "maybe later",
    "not at the moment",
    "need to wait",
    "waiting for payday",
    "payday isn't until",
    "payday isnt until",
    "short on cash",
    "strapped for cash",
    "funds are tight",
    "tight budget",
    "it's out of my budget",
    "its out of my budget",
    "over my budget",
    "outside my budget",
    "can't spare the money",
    "cant spare the money",
    "don't have the funds",
    "do not have the funds",
    "i dont have the funds",
    "i do not have the funds",
    "i aint got 300",
    "i ain't got 300",
    "aint got it",
    "ain't got it",
    "money is tight",
    "money's tight",
    "money is short",
    "money's short",
    "short on funds",
    "low on funds",
    "no spare cash",
    "i have no spare cash",
    "i dont have any spare cash",
    "i do not have any spare cash",
]
